using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.AspNetCore.Razor.TagHelpers;

namespace Sakura.AspNetCore.Mvc.TagHelpers
{
	/// <summary>
	/// Provide base implementation for all pager tag helpers that provide additional setting items.
	/// </summary>
	public abstract class PagerSettingTagHelper : TagHelper
	{
		#region Order

		/// <summary>
		/// Get the default <see cref="Order"/> value for this tag helper. This field is constant.
		/// </summary>
		public const int DefaultOrder = PagerTagHelper.DefaultOrder;

		/// <inheritdoc />
		public override int Order { get; } = DefaultOrder;

		#endregion

		#region Core Method

		/// <summary>
		/// Apply the all setting items generated by this tag.
		/// </summary>
		/// <returns>The generated key-value pairs of settings.</returns>
		public abstract void ApplySettings(IDictionary<string, string> settings);

		#endregion

		/// <summary>
		/// Get the current settings before this tag helper is applied.
		/// </summary>
		[HtmlAttributeName(PagerTagHelper.SettingsAttributeName, DictionaryAttributePrefix = PagerTagHelper.SettingsAttributePerfix)]
		public Dictionary<string, string> Settings { get; set; }

		/// <inheritdoc />
		public override void Process(TagHelperContext context, TagHelperOutput output)
		{
			ApplySettings(Settings);
		}
	}
}
