using System;
using System.Collections.Generic;
using System.Text;
using Microsoft.AspNetCore.Razor.TagHelpers;

namespace Sakura.AspNetCore.Mvc.TagHelpers
{
	/// <summary>
	/// Provide base implementation for all pager tag helpers that provide additional setting items.
	/// </summary>
	public abstract class PagerSettingTagHelper : TagHelper
	{
		#region Order

		/// <summary>
		/// Get the default <see cref="Order"/> value for this tag helper. This field is constant.
		/// </summary>
		public const int DefaultOrder = PagerTagHelper.DefaultOrder;

		/// <inheritdoc />
		public override int Order { get; } = DefaultOrder;

		#endregion

		#region Core Method

		/// <summary>
		/// Get the all setting items generated by this tag.
		/// </summary>
		/// <returns>The generated key-value pairs of settings.</returns>
		public abstract IEnumerable<KeyValuePair<string, string>> GetSettings(); 

		#endregion

		/// <inheritdoc />
		public override void Process(TagHelperContext context, TagHelperOutput output)
		{
			foreach (var item in GetSettings())
			{
				output.Attributes.SetAttribute(PagerTagHelper.SettingsAttributePerfix + item.Key, item.Value);
			}
		}
	}
}
